apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: example-with-approval
  namespace: default
spec:
  params:
  - name: CM_APPROVER_DEV
  steps:
  - name: approval-1
    image: tmaxcloudck/approval-watcher:0.0.1
    imagePullPolicy: Always
    volumeMounts:
    - name: approver-list-dev
      mountPath: /tmp/config
  volumes:
  - name: approver-list-dev
    configMap:
      name: $(params.CM_APPROVER_DEV)
