apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: third-task-run
spec:
  serviceAccountName: approval-sa
  taskRef:
    name: third-task
  params:
  - name: third-user-1
    value: approver-dev
  - name: third-user-2
    value: approver-dev
  - name: mail-title-1
    value: "[배포 승인 요청] approval-test-app 배포 승인 요청"
  - name: mail-content-1
    value: |
            approval-test 환경에 QA 배포 예정

            배포를 위한 승인이 필요합니다
  - name: mail-title-2
    value: "[배포 확인 요청] approval-test-app 테스트 후 승인 요청"
  - name: mail-content-2
    value: |
            approval-test 환경에 QA 배포 완료

            테스트 후 승인이 필요합니다
  - name: app-name
    value: approval-test-app
  - name: image-url
    value: ubuntu:latest
  - name: deploy-namespace
    value: default
  resources:
    inputs:
    - name: image
      resourceSpec:
        type: image
        params:
        - name: url
          value: ubuntu:latest
