apiVersion: v1
kind: ServiceAccount
metadata:
  name: approval-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: approval-role
  namespace: approval-test
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: approval-role
  namespace: approval-op
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: approval-rolebinding
  namespace: approval-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: approval-role
subjects:
  - kind: ServiceAccount
    name: approval-sa
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: approval-rolebinding
  namespace: approval-op
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: approval-role
subjects:
  - kind: ServiceAccount
    name: approval-sa
    namespace: default
