apiVersion: apps/v1
kind: Deployment
metadata:
  name: approval-proxy-server
  namespace: approval-system
spec:
  selector:
    matchLabels:
      app: approval-proxy-server
  template:
    metadata:
      labels:
        app: approval-proxy-server
    spec:
      serviceAccountName: approval-watcher
      containers:
        - name: proxy-server
          image: tmaxcloudck/approval-watcher:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 400m
              memory: 400Mi
