apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: approval-watcher
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tmax.io
  resources:
  - 'approvals'
  - 'approvals/status'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
