kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: approval-watcher
subjects:
- kind: ServiceAccount
  name: approval-watcher
  namespace: approval-system
roleRef:
  kind: ClusterRole
  name: approval-watcher
  apiGroup: rbac.authorization.k8s.io
