apiVersion: v1
kind: Service
metadata:
  name: approval-proxy-server
  namespace: approval-system
spec:
  selector:
    app: approval-proxy-server
  ports:
    - name: legacy
      port: 80
      targetPort: 10999
    - name: extension-api-server
      port: 443
